# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 16:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
                ('message', models.CharField(default='Sans Message', max_length=555)),
                ('nom', models.CharField(default='Sans Nom', max_length=255)),
                ('lien', models.CharField(default='Sans lien', max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Contestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contenu', models.CharField(default='Sans Motif', max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjeu_perso', models.CharField(default='Sans Enjeu', max_length=500)),
                ('prive', models.BooleanField(default=False)),
                ('etat', models.CharField(choices=[('D', 'Default'), ('E', 'Envoyé'), ('A', 'Accepté'), ('EX', 'Expiré'), ('R', 'Refusé'), ('AV', 'Attente de Validation'), ('V', 'Validé'), ('C', 'Contesté'), ('S', 'Signalé')], default='D', max_length=2)),
                ('date_envoie', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
                ('date_acceptation', models.DateTimeField(null=True)),
                ('date_execution', models.DateTimeField(null=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('expire', models.BooleanField(default=False)),
                ('warning_triche', models.BooleanField(default=False)),
                ('warning_analyse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libelle_Defi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Sans Titre', max_length=255)),
                ('description', models.CharField(default='Sans Description', max_length=5000)),
                ('nb_mins', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Libelle_Quete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif', models.CharField(default='Sans Titre', max_length=255)),
                ('description', models.CharField(default='Sans Description', max_length=5000)),
                ('duree', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='MAJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
            ],
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(default='rien', max_length=255)),
                ('y', models.CharField(default='rien', max_length=255)),
                ('id_osm', models.CharField(default='rien', max_length=255)),
                ('nom', models.CharField(default='rien', max_length=255)),
                ('attribut', models.CharField(default='rien', max_length=855)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('drapeau', models.ImageField(upload_to='image/utilisateurs/drapeau')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DA', "Demande d'ami"), ('D', 'Defi'), ('Q', 'Quête'), ('C', 'Contest')], default='D', max_length=2)),
                ('message', models.CharField(max_length=1000)),
                ('lien', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
                ('active', models.BooleanField(default=True)),
                ('vue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='image/thumbs/')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Preuve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(null=True, upload_to='defi/preuve')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition_Defi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Sans Titre', max_length=255)),
                ('description', models.CharField(default='Sans Titre', max_length=5000)),
                ('etat', models.CharField(choices=[('E', 'Envoyé'), ('D', 'Default'), ('V', 'Validé'), ('S', 'Signalé')], default='E', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('etat', models.CharField(choices=[('D', 'Default'), ('V', 'Validé'), ('S', 'Signalé')], default='D', max_length=2)),
                ('date_debut', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
                ('date_fin', models.DateTimeField(null=True)),
                ('expire', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('decoration', models.CharField(default="<span class='ti-bolt'> </span>", max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('goodies', models.BooleanField(default=False)),
                ('goodies_description', models.CharField(default='Sans Goodies', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(default='Sans Motif', max_length=555)),
                ('nom', models.CharField(default='Sans Nom', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Sans Nom', max_length=255)),
                ('photo_team', models.ImageField(null=True, upload_to='image/team/profil')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('descritption', models.CharField(default=' ', max_length=255)),
                ('couleur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.BooleanField(default=False)),
                ('derniere_connexion', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 18, 1, 18, 460205))),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('email_valide', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=0)),
                ('score_absolu', models.IntegerField(default=0)),
                ('score_race', models.IntegerField(default=0)),
                ('score_cuisine', models.IntegerField(default=0)),
                ('score_sport', models.IntegerField(default=0)),
                ('score_extreme', models.IntegerField(default=0)),
                ('score_social_environnement', models.IntegerField(default=0)),
                ('score_autre', models.IntegerField(default=0)),
                ('score_arts', models.IntegerField(default=0)),
                ('nom_entier', models.CharField(default='Sans Nom', max_length=255)),
                ('info', models.CharField(default='Sans description', max_length=255)),
                ('amis', models.ManyToManyField(to='CC.Utilisateur')),
                ('pa', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pa', to='CC.Photo')),
                ('pp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='CC.Photo')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='membres',
            field=models.ManyToManyField(default=None, related_name='user', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='sous_theme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Theme'),
        ),
        migrations.AddField(
            model_name='quete',
            name='challengeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='quete',
            name='libelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Libelle_Quete'),
        ),
        migrations.AddField(
            model_name='proposition_defi',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepteur', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='libelle_quete',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='libelle_quete',
            name='defis',
            field=models.ManyToManyField(to='CC.Libelle_Defi'),
        ),
        migrations.AddField(
            model_name='libelle_quete',
            name='recompense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Recompense'),
        ),
        migrations.AddField(
            model_name='libelle_quete',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CC.Theme'),
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='recompense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Recompense'),
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='sous_theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CC.Sous_Theme'),
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CC.Theme'),
        ),
        migrations.AddField(
            model_name='demandeami',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeur', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='demandeami',
            name='recepteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amidemande', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='defi',
            name='challengeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengeurdefi', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='defi',
            name='contestation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CC.Contestation'),
        ),
        migrations.AddField(
            model_name='defi',
            name='defieur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defieurdefi', to='CC.Utilisateur'),
        ),
        migrations.AddField(
            model_name='defi',
            name='libelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Libelle_Defi'),
        ),
        migrations.AddField(
            model_name='defi',
            name='preuve',
            field=models.ManyToManyField(to='CC.Preuve'),
        ),
        migrations.AddField(
            model_name='defi',
            name='signalement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CC.Signalement'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='personne_concernee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CC.Utilisateur'),
        ),
    ]
