# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-26 14:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 16, 15, 13, 317075)),
        ),
    ]
