# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='categorie',
            field=models.CharField(default='rien', max_length=255),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='sous_categorie',
            field=models.CharField(default='rien', max_length=255),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 16, 37, 1, 552604)),
        ),
    ]
