# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0002_auto_20170825_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 20, 39, 30, 141068)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='pa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pa', to='CC.Photo'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pp', to='CC.Photo'),
        ),
    ]
