# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0002_auto_20170902_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libelle_defi',
            name='nb_mins',
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='duree_acceptation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libelle_defi',
            name='duree_execution',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 41, 30, 698793)),
        ),
    ]
