# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0003_auto_20170913_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 19, 36, 47, 63482)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='latitude',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='longitude',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
