# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0005_auto_20170913_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='eclairs',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 22, 33, 31, 596021)),
        ),
    ]
