# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0006_auto_20170913_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='defi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CC.Libelle_Defi'),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
        migrations.AlterField(
            model_name='quete',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 12, 34, 3, 443930)),
        ),
    ]
