# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0007_auto_20170914_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libelle_quete',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='libelle_quete',
            name='defis',
        ),
        migrations.RemoveField(
            model_name='libelle_quete',
            name='recompense',
        ),
        migrations.RemoveField(
            model_name='libelle_quete',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='quete',
            name='challengeur',
        ),
        migrations.RemoveField(
            model_name='quete',
            name='libelle',
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 14, 37, 47, 680329)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 14, 37, 47, 680329)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 14, 37, 47, 680329)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 14, 37, 47, 680329)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 14, 37, 47, 680329)),
        ),
        migrations.DeleteModel(
            name='Libelle_Quete',
        ),
        migrations.DeleteModel(
            name='Quete',
        ),
    ]
