# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 14:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0008_auto_20170914_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='libelle_defi',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 16, 4, 24, 384140)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 16, 4, 24, 384140)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 16, 4, 24, 384140)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 16, 4, 24, 384140)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 14, 16, 4, 24, 384140)),
        ),
    ]
