# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-20 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC', '0012_auto_20170920_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='score_arts',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='score_extreme',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='score_social_environnement',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_citoyen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_creation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_elite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='score_gaming',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 19, 10, 6, 579650)),
        ),
        migrations.AlterField(
            model_name='defi',
            name='date_envoie',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 19, 10, 6, 579650)),
        ),
        migrations.AlterField(
            model_name='maj',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 19, 10, 6, 579650)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 19, 10, 6, 579650)),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 20, 19, 10, 6, 579650)),
        ),
    ]
